-- Short-lived Cloudflare-authorised device grants.
-- The grant is bound to the authenticated CF session and a public key
-- generated by the browser on the DMZ origin.
CREATE TABLE IF NOT EXISTS dmz_grants (
    id TEXT PRIMARY KEY,
    session_id TEXT NOT NULL,
    handoff_id TEXT NOT NULL,
    device_public_key TEXT NOT NULL,
    created_at INTEGER NOT NULL,
    expires_at INTEGER NOT NULL,
    used_at INTEGER
);

CREATE INDEX IF NOT EXISTS idx_dmz_grants_session_id
    ON dmz_grants(session_id);

CREATE INDEX IF NOT EXISTS idx_dmz_grants_expires_at
    ON dmz_grants(expires_at);

-- Prevent replay of authenticated DMZ service requests.
CREATE TABLE IF NOT EXISTS dmz_request_nonces (
    nonce TEXT PRIMARY KEY,
    expires_at INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_dmz_request_nonces_expires_at
    ON dmz_request_nonces(expires_at);
